namespace: fredericpetit
name: freebox_auth
version: 0.0.1
readme: README.md
authors:
  - "Frédéric Petit @fredericpetit"
description: "Ansible role for getting a Freebox API Token."
repository: "https://gitlab.com/fredericpetit/ansible-role-freebox-auth"
documentation: "https://gitlab.com/fredericpetit/ansible-role-freebox-auth"
license:
  - MIT
dependencies: {}
tags:
  - free
  - box
  - freebox
  - auth
  - token
  - security
